[project]
name = "pocketmapper"
version = "0.0.2-rc0"
dependencies = [
    "bio",
    "fire",
    "numpy",
    "pandas",
    "tqdm",
]
requires-python = ">=3.12"
authors = [
  {name="Lachlan Ellingboe", email="Lachlan.Ellingboe@icr.ac.uk"},
]
description = "A tool for mapping surface pockets in PDB structures"
readme = "README.md"
license = "MIT"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
]


[project.optional-dependencies]
dev = [
  "black",
  "bump2version",
  "pre-commit",
  "flake8",
]

[project.scripts]
pocketmapper_cli = "pocketmapper:main"

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py312']
skip-string-normalization = false
line-length = 120
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | build
    | dist
  )/
)
'''

[tool.flake8]
max-line-length = 120
exclude = "__init__.py,build,.eggs"