[metadata]
name = pocketmapper
version = 0.0.1
author = Lachlan Ellingboe
author_email = Lachlan.Ellingboe@icr.ac.uk

license = MIT
description = A simple Python package
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Development Status :: 2 - Pre-Alpha
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Operating System :: OS Independent
    License :: OSI Approved :: MIT License


[options]
zip_safe = False
packages = find:
python_requires = >=3.7
setup_requires =
	setuptools_scm

[options.packages.find]
where = tmp
exclude = test*

[options.extras_require]
dev =
	black
	bump2version
	pre-commit
	flake8

[flake8]
max-line-length = 79
exclude = __init__.py,build,.eggs
